#!/usr/bin/env bash
# configure web-02 to be identical with web-01

# install nginx and allow ufw in port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Make site content folders with permission
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Holberton School' |sudo tee  /var/www/html/index.html

# Custom error page 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# page redirection and custom header
redirect_config="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/github.com permanent;"
sudo sed -i "s/server_name _;/$redirect_config/" /etc/nginx/sites-enabled/default

# custom 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
