#!/usr/bin/env bash
#Distribute traffic to web-01 & web-02 servers through lb-01 HAProxy


# Install & configure HAproxy on lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# append lb config to config file
config=\
"
frontend mich_front
        bind *:80
        mode http
        default_backend mich_back

backend mich_back
        balance roundrobin
        server 6414-web-01 3.93.240.46:80 check
        server 6414-web-02 54.227.209.123:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable init script startup for haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# confirm config is valid and restart haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
